### ISSUE TITLE
Doesn't run my app unless I modify a file

### ISSUE THREAD

**Issue by fmpwizard** [AgentCosmic/xnotify#1]
Hi,

Great little project! I just tried it using:

```
xnotify -i . -e "(vendor|\.git)" --verbose   -- go build github.com/user/repo -- ./repo -logtostderr
```

and I see it finds all the files to watch but it doesn't run `./repo -logtostderr`

To make it run it, I had to manually edit at least one file, and then it runs my program.
I was expecting it to run my program from the start, and restart it when I make changes.

Thanks

**Comment by AgentCosmic** [comment]
That's a great point! I've added the `--trigger` option so you can run the command immediately. You can download the new version at the release page. Feel free to open this issues if you have any problem.
