### ISSUE TITLE
fatal error: all goroutines are asleep - deadlock!

### ISSUE THREAD

**Issue by floodico** [AgentCosmic/xnotify#3]
Hi there!  When i trying to start it on my client
> xnotify --listen "0.0.0.0.8090"

then it's going to be raised 
````
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive (nil chan)]:
main.(*program).action(0xc0000e0000, 0xc0000bc840, 0x84b80b, 0xa)
	D:/Studio/Code/xnotify/xnotify.go:206 +0x753
gopkg.in/urfave/cli%2ev1.HandleAction(0x7c1940, 0xc000060cd0, 0xc0000bc840, 0xc00006a300, 0x0)
	C:/Users/dalto/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0xc8
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00008cea0, 0xc00001e180, 0x3, 0x3, 0x0, 0x0)
	C:/Users/dalto/go/pkg/mod/gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x58c
main.main()
	D:/Studio/Code/xnotify/xnotify.go:115 +0x8bf

goroutine 6 [chan receive]:
main.(*program).execLoop(0xc0000e0000)
	D:/Studio/Code/xnotify/xnotify.go:426 +0x37
created by main.(*program).action
	D:/Studio/Code/xnotify/xnotify.go:192 +0x6cf
````
 I'm running it on Vagrant virtual system. 
Distro: Ubuntu 18.04.4 LTS. 
Kernel: 4.15.0-118-generic x86_64
Used binary release: https://github.com/AgentCosmic/xnotify/releases/download/v0.2.3/xnotify-linux-amd64.

When I run `xnotify` on my host then it looks like it starts well. 
> ./xnotify --client ":8090" -i .

Host system: MacOS Catalina 10.15.4
Used binary release: https://github.com/AgentCosmic/xnotify/releases/download/v0.2.3/xnotify-darwin-amd64.

**Comment by AgentCosmic** [comment]
Hi, can you try this version and let me know if it works.

[releases.zip](https://github.com/AgentCosmic/xnotify/files/5340984/releases.zip)

**Comment by floodico** [comment]
@AgentCosmic thanks for the quick response ;)
> releases.zip

I tried these binaries and still this isn't working for Linux. Got the same error.

**Comment by AgentCosmic** [comment]
Let's hope this works:
[xnotify-linux-amd64.zip](https://github.com/AgentCosmic/xnotify/files/5345291/xnotify-linux-amd64.zip)

**Comment by floodico** [comment]
I specified an incorrect address `"0.0.0.0.8090"` instead of `"0.0.0.0:8090"`.
Sorry for my fault... With the correct input it works well.
