### ISSUE TITLE
When the file changes, the event is dispatched 4 times.

### ISSUE THREAD

**Issue by LordKino** [AgentCosmic/xnotify#5]
Version 0.2.4, windows amd64
When the file changes, the event is dispatched 4 times.

.\xnotify.exe --verbose --client 192.168.56.101:8090 -i . -e "(vendor|\.git)$"

output:
......
[xnotify] Watching: C:\localhost\laravel\xnotify.exe
**write rsync.sh
write rsync.sh
write rsync.sh
write rsync.sh**

**Comment by AgentCosmic** [comment]
What's writing the file? Some text editors make multiple writes when you save. You can try modifying the file via cli to see if it still happens.

**Comment by LordKino** [comment]
Netbeans, Notepad++ with same result

**Comment by AgentCosmic** [comment]
I've not used those before. But have you tried writing to a file via cli? If that only trigger once then it's probably the editor that's writing multiple times.

**Comment by LordKino** [comment]
Tried  Vim:
........
[xnotify] Watching: C:\localhost\laravel\xnotify.exe

write rsync.sh
write rsync.sh~
write rsync.sh
write rsync.sh~
write rsync.sh
write .rsync.sh.swp

**Comment by AgentCosmic** [comment]
Yeah look like it's working fine since the `.swp` file is triggering only once. It'll be better if you can do something like `echo 123 > file.txt` to be sure.

**Comment by LordKino** [comment]
Yes, 1 line:

Write file.txt

**Comment by AgentCosmic** [comment]
👍 There's nothing much I can do about editors triggering multiple write events. You can try using the `--batch` option. I'll close the issue.
