### ISSUE TITLE
Hacktoberfest: Update dependencies and Go version

### ISSUE THREAD

**Issue by AgentCosmic** [AgentCosmic/xnotify#7]
Looking for a contributor to help update dependencies and Go to latest version, and test that everything is working fine.

**Comment by elliotwutingfeng** [comment]
I'm interested!

**Comment by AgentCosmic** [comment]
Awesome. Just create a fork of this repo. Make the changes and submit a PR linking this issue. Do test it to make sure nothing's broken. Thanks.

**Comment by elliotwutingfeng** [comment]
Are you looking for test cases?

**Comment by AgentCosmic** [comment]
Smoke testing is fine enough. If you're up for test cases you can submit in a different PR 😊
